### ISSUE TITLE
Fix the README

### ISSUE THREAD

**Issue by 3reetop** [3reetop/website#1]
So I'm a lazy shit (I'll admit it) and I decided not to update the README.

Right now the README says that the site is powered by Cloudflare Pages, however this is false. The site is actually powered by Workers Sites, because Cloudflare Pages does not support using a `*.eu.org` subdomain as a TLD.

I should update the README to reflect this change.

**Comment by 96RadhikaJadhav** [comment]
@3reetop Can I work on it?

**Comment by 3reetop** [comment]
> @3reetop Can I work on it?

Feel free to fork the repository and make a pull request! Right now I just want the README to correctly clarify that the site is using Cloudflare Workers Sites and not Cloudflare Pages

**Comment by 96RadhikaJadhav** [comment]
@3reetop What should be the link used in line 10 of README instead of https://pages.cloudflare.com ?

**Comment by 3reetop** [comment]
> @3reetop What should be the link used in line 10 of README instead of https://pages.cloudflare.com ?

you can make it link to https://developers.cloudflare.com/workers/platform/sites

**Comment by 3reetop** [comment]
Oops, forgot to close this issue. Thanks again for your contribution!
